Rails:
  Enabled: true

inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Style/StringLiterals:
  Enabled: false
