language: ruby
cache: bundler
sudo: required
bundler_args: --without production
before_install:
  - gem update --system
  - gem install bundler --pre
before_script:
  - bin/bundle exec bin/travis
rvm:
  - 2.4.2
jdk:
  - oraclejdk8

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
