default: &default
  adapter: sqlite3
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
<% if Swapmeet.config.db&.url %>
  url: <%= Swapmeet.config.db.url %>
<% else %>
  database: db/development.sqlite3
<% end %>

test:
  <<: *default
  database: db/test.sqlite3

production:
  url: <%= Swapmeet.config.db&.url %>
