# Settings appropriate for running Swapmeet in development

# Make sure that any reloaded presenters are looked up on each request.
cache_presenters: true

# Use sqlite by default in development so it's zero-config
keycard:
  database:
    adapter: sqlite
    database: db/keycard_development.sqlite3

checkpoint:
  database:
    adapter: sqlite
    database: db/checkpoint_development.sqlite3
